services:
  - type: web
    name: acad-track
    env: php
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      php artisan storage:link || true
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
