services:
  - type: web
    name: acad-track
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate || true
      mkdir -p database
      touch database/database.sqlite
      chmod 666 database/database.sqlite
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://acad-track.onrender.com
